#!/bin/bash
set -e

PLEX_MEDIA_DIR=${PLEX_MEDIA_DIR:-/home/hidka/Media/plex}

MOVIEPILOT_BASE_URL=${MOVIEPILOT_BASE_URL:-http://your_mp_url}
MOVIEPILOT_USER=${MOVIEPILOT_USER:-admin}
MOVIEPILOT_PASSWORD=${MOVIEPILOT_PASSWORD:-password}
MOVIEPILOT_DELETE_SRC=${MOVIEPILOT_DELETE_SRC:-false}
MOVIEPILOT_DELETE_DEST=${MOVIEPILOT_DELETE_DEST:-false}

QBITTORRENT_BASE_URL=${QBITTORRENT_BASE_URL:-http://you_qb_url}
QBITTORRENT_USER=${QBITTORRENT_USER:-hidka}
QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD:-password}

mkdir -p "/config"
cat > "/config/MediaJanitor.conf" <<EOF
[plex]
MEDIA_DIR = ${PLEX_MEDIA_DIR}

[moviepilot]
BASE_URL = ${MOVIEPILOT_BASE_URL}
USER = ${MOVIEPILOT_USER}
PASSWORD = ${MOVIEPILOT_PASSWORD}
DELETE_SRC = ${MOVIEPILOT_DELETE_SRC}
DELETE_DEST = ${MOVIEPILOT_DELETE_DEST}

[qbittorrent]
BASE_URL = ${QBITTORRENT_BASE_URL}
USER = ${QBITTORRENT_USER}
PASSWORD = ${QBITTORRENT_PASSWORD}
EOF

cd /
exec python3 -m app.main